# Generated by Django 4.2.26 on 2026-03-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_internship', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('college', models.CharField(max_length=200)),
                ('university_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
