# Generated by Django 4.2.26 on 2026-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='contact_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='registration_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='internshipapplication',
            constraint=models.UniqueConstraint(fields=('registration_number', 'title_of_internship'), name='unique_student_internship_application'),
        ),
    ]
